// tools/db/spikes/partner-sig/gen-vectors.ts
//
// Emits the test vectors for the database-side signature spike (partner_sig_spike.sql) as SQL INSERTs on stdout. Run by run.sh; needs only Deno and
// no network, no import map and no lockfile (the one import is the in-tree software authenticator, which itself imports nothing).
//
//   deno run tools/db/spikes/partner-sig/gen-vectors.ts [--es256-valid N] [--rs256-valid N] > vectors.sql
//
// Every vector carries `expect`: what a CORRECT verifier must answer. Valid signatures come from the software authenticator's real WebAuthn assertions
// (message = authenticatorData || SHA-256(clientDataJSON), the bytes a relying party verifies) or from Web Crypto directly; the refusals are one-fault
// mutations of a valid vector, or signatures deliberately built wrong (a SHA-384 DigestInfo, a Bleichenbacher-shaped padding). Keys are fresh on every
// run, so a pass is not an artefact of one lucky key; the one fixed vector is the RFC 6979 A.2.5 known answer, which does not depend on Web Crypto.

import { concat, fromB64u, SoftwareAuthenticator } from "../../../../supabase/tests/deno-unit/software-authenticator.ts";

const args = new Map<string, string>();
for (let i = 0; i < Deno.args.length; i += 2) args.set(Deno.args[i]!, Deno.args[i + 1]!);
const N_ES = Number(args.get("--es256-valid") ?? 10);
const N_RS = Number(args.get("--rs256-valid") ?? 6);

const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
const fromHex = (h: string) => Uint8Array.from(h.match(/../g) ?? [], (x) => parseInt(x, 16));
const lit = (b: Uint8Array) => `'\\x${hex(b)}'`;
const sha256 = async (d: Uint8Array) => new Uint8Array(await crypto.subtle.digest("SHA-256", d as Uint8Array<ArrayBuffer>));

function row(alg: "ES256" | "RS256", label: string, expect: boolean, k1: Uint8Array, k2: Uint8Array, msg: Uint8Array, sig: Uint8Array, source: string): void {
  console.log(`INSERT INTO spike_sig.vector (alg, label, expect, k1, k2, msg, sig, source) VALUES ('${alg}', '${label.replaceAll("'", "''")}', ${expect}, ${lit(k1)}, ${lit(k2)}, ${lit(msg)}, ${lit(sig)}, '${source}');`);
}

/** DER Ecdsa-Sig-Value from two big-endian magnitudes (minimal, positive). */
function derSig(r: Uint8Array, s: Uint8Array): Uint8Array {
  const int = (b: Uint8Array): Uint8Array => {
    let i = 0;
    while (i < b.length - 1 && b[i] === 0) i++;
    let v: Uint8Array = b.slice(i);
    if (v[0]! & 0x80) v = concat(Uint8Array.of(0), v);
    return concat(Uint8Array.of(0x02, v.length), v);
  };
  const body = concat(int(r), int(s));
  return concat(Uint8Array.of(0x30, body.length), body);
}

/** r, s from a DER signature produced by our own encoder (single-byte lengths). */
function derParts(sig: Uint8Array): [Uint8Array, Uint8Array] {
  const rl = sig[3]!;
  const r = sig.slice(4, 4 + rl);
  const sl = sig[5 + rl]!;
  return [r, sig.slice(6 + rl, 6 + rl + sl)];
}

const bigOf = (b: Uint8Array) => BigInt("0x" + (hex(b) || "0"));
const bytesOf = (n: bigint, len: number) => fromHex(n.toString(16).padStart(len * 2, "0"));
const N_P256 = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551n;
const P_P256 = 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffffn;

async function assertion(auth: SoftwareAuthenticator): Promise<{ msg: Uint8Array; sig: Uint8Array }> {
  const challenge = crypto.getRandomValues(new Uint8Array(32));
  const r = await auth.assert({ rpId: "partners.example.test", origin: "https://partners.example.test", challenge });
  const authData = fromB64u(r.response.authenticatorData);
  const cd = fromB64u(r.response.clientDataJSON);
  return { msg: concat(authData, await sha256(cd)), sig: fromB64u(r.response.signature) };
}

console.log("-- generated by gen-vectors.ts; fresh keys on every run. Do not commit.");
console.log("BEGIN;");

// ----- ES256 --------------------------------------------------------------------------------------------------------------------------------
const SA = "software-authenticator";
const es: SoftwareAuthenticator[] = [];
for (let i = 0; i < N_ES; i++) es.push(await SoftwareAuthenticator.create("ES256"));
const esOther = await SoftwareAuthenticator.create("ES256");
for (const a of es) {
  const { msg, sig } = await assertion(a);
  const { x, y } = a.keyParams;
  row("ES256", "valid", true, x!, y!, msg, sig, SA);
}
{
  const a = es[0]!;
  const { msg, sig } = await assertion(a);
  const { x, y } = a.keyParams;
  const flip = (b: Uint8Array, at: number) => Uint8Array.from(b, (v, i) => (i === (at < 0 ? b.length + at : at) ? v ^ 1 : v));
  const [r, s] = derParts(sig);
  row("ES256", "valid-high-s (n - s: still a valid ECDSA signature; WebAuthn does not require low-s)", true, x!, y!, msg, derSig(r, bytesOf(N_P256 - bigOf(s), 32)), SA);
  row("ES256", "bad: last signature bit flipped", false, x!, y!, msg, flip(sig, -1), SA);
  row("ES256", "bad: one message bit flipped", false, x!, y!, flip(msg, 5), sig, SA);
  row("ES256", "bad: another authenticator's key", false, esOther.keyParams.x!, esOther.keyParams.y!, msg, sig, SA);
  row("ES256", "bad: r = 0", false, x!, y!, msg, derSig(new Uint8Array(32), s), SA);
  row("ES256", "bad: s = 0", false, x!, y!, msg, derSig(r, new Uint8Array(32)), SA);
  row("ES256", "bad: s = n", false, x!, y!, msg, derSig(r, bytesOf(N_P256, 32)), SA);
  row("ES256", "bad: r = n", false, x!, y!, msg, derSig(bytesOf(N_P256, 32), s), SA);
  row("ES256", "bad: DER with a redundant leading zero in r", false, x!, y!, msg, concat(Uint8Array.of(0x30, sig[1]! + 1, 0x02, sig[3]! + 1, 0x00), sig.slice(4)), SA);
  row("ES256", "bad: DER with trailing garbage", false, x!, y!, msg, concat(sig, Uint8Array.of(0)), SA);
  row("ES256", "bad: DER with the wrong outer tag", false, x!, y!, msg, concat(Uint8Array.of(0x31), sig.slice(1)), SA);
  row("ES256", "bad: raw r||s instead of DER", false, x!, y!, msg, concat(bytesOf(bigOf(r), 32), bytesOf(bigOf(s), 32)), SA);
  row("ES256", "bad: public key off the curve (y + 1)", false, x!, bytesOf(bigOf(y!) + 1n, 32), msg, sig, SA);
  row("ES256", "bad: public key coordinate x = p (not reduced)", false, bytesOf(P_P256, 32), y!, msg, sig, SA);
  row("ES256", "bad: empty signature", false, x!, y!, msg, new Uint8Array(0), SA);
}
// Degenerate public keys, signed with a tiny independent BigInt ECDSA (affine arithmetic, written separately from the SQL): d = 1 makes Q = G, so the
// verifier's precomputed G + Q is a DOUBLING (the P = Q branch of the add routine), and d = n - 1 makes Q = -G, so G + Q is the point at infinity
// (the P = -Q branch). Both must still verify; both exercise code that a random key never reaches.
{
  const GX = 0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296n;
  const GY = 0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5n;
  type Pt = [bigint, bigint] | null;
  const mod = (a: bigint, m: bigint) => ((a % m) + m) % m;
  const inv = (a: bigint, m: bigint) => {
    let [r0, r1, s0, s1] = [mod(a, m), m, 1n, 0n];
    while (r1 !== 0n) {
      const q = r0 / r1;
      [r0, r1] = [r1, r0 - q * r1];
      [s0, s1] = [s1, s0 - q * s1];
    }
    return mod(s0, m);
  };
  const add = (a: Pt, b: Pt): Pt => {
    if (a === null) return b;
    if (b === null) return a;
    if (a[0] === b[0] && mod(a[1] + b[1], P_P256) === 0n) return null;
    const l = a[0] === b[0] ? mod((3n * a[0] * a[0] - 3n) * inv(2n * a[1], P_P256), P_P256) : mod((b[1] - a[1]) * inv(b[0] - a[0], P_P256), P_P256);
    const x = mod(l * l - a[0] - b[0], P_P256);
    return [x, mod(l * (a[0] - x) - a[1], P_P256)];
  };
  const mul = (k: bigint, pt: Pt): Pt => {
    let r: Pt = null;
    let q = pt;
    while (k > 0n) {
      if (k & 1n) r = add(r, q);
      q = add(q, q);
      k >>= 1n;
    }
    return r;
  };
  const sign = async (d: bigint, msg: Uint8Array): Promise<Uint8Array> => {
    const z = bigOf(await sha256(msg));
    for (;;) {
      const k = mod(bigOf(crypto.getRandomValues(new Uint8Array(32))), N_P256);
      if (k === 0n) continue;
      const r = mod(mul(k, [GX, GY])![0], N_P256);
      const sv = mod(inv(k, N_P256) * (z + r * d), N_P256);
      if (r !== 0n && sv !== 0n) return derSig(bytesOf(r, 32), bytesOf(sv, 32));
    }
  };
  for (const [label, d, qy] of [
    ["valid: public key = G (d = 1): G + Q is a doubling", 1n, GY],
    ["valid: public key = -G (d = n - 1): G + Q is the point at infinity", N_P256 - 1n, P_P256 - GY],
  ] as const) {
    const msg = crypto.getRandomValues(new Uint8Array(69));
    row("ES256", label, true, bytesOf(GX, 32), bytesOf(qy, 32), msg, await sign(d, msg), "bigint-ecdsa");
  }
}
// RFC 6979 A.2.5: ECDSA P-256 with SHA-256, message "sample" (a known answer that does not depend on Web Crypto)
row(
  "ES256",
  "valid: RFC 6979 A.2.5 known answer (P-256, SHA-256, message 'sample')",
  true,
  fromHex("60fed4ba255a9d31c961eb74c6356d68c049b8923b61fa6ce669622e60f29fb6"),
  fromHex("7903fe1008b8bc99a41ae9e95628bc64f2f1b20c2d7e9f5177a3c294d4462299"),
  new TextEncoder().encode("sample"),
  derSig(fromHex("efd48b2aacb6a8fd1140dd9cd45e81d69d2c877b56aaf991c34d0ea84eaf3716"), fromHex("f7cb1c942d657c41d436c7a1b6e29f65f3e900dbb9aff4064dc4ab2f843acda8")),
  "RFC 6979",
);

// ----- RS256 --------------------------------------------------------------------------------------------------------------------------------
const rs: SoftwareAuthenticator[] = [];
for (let i = 0; i < N_RS; i++) rs.push(await SoftwareAuthenticator.create("RS256"));
const rsOther = await SoftwareAuthenticator.create("RS256");
for (const a of rs) {
  const { msg, sig } = await assertion(a);
  row("RS256", "valid (2048-bit)", true, a.keyParams.n!, a.keyParams.e!, msg, sig, SA);
}
{
  const a = rs[0]!;
  const { msg, sig } = await assertion(a);
  const { n, e } = a.keyParams;
  const flip = (b: Uint8Array, at: number) => Uint8Array.from(b, (v, i) => (i === (at < 0 ? b.length + at : at) ? v ^ 1 : v));
  row("RS256", "bad: last signature bit flipped", false, n!, e!, msg, flip(sig, -1), SA);
  row("RS256", "bad: one message bit flipped", false, n!, e!, flip(msg, 5), sig, SA);
  row("RS256", "bad: another authenticator's key", false, rsOther.keyParams.n!, rsOther.keyParams.e!, msg, sig, SA);
  row("RS256", "bad: signature one byte short", false, n!, e!, msg, sig.slice(1), SA);
  row("RS256", "bad: signature equal to the modulus", false, n!, e!, msg, n!, SA);
  row("RS256", "bad: signature all 0xff (above the modulus)", false, n!, e!, msg, new Uint8Array(256).fill(0xff), SA);
  row("RS256", "bad: signature = 1", false, n!, e!, msg, bytesOf(1n, 256), SA);
  row("RS256", "bad: signature = 0", false, n!, e!, msg, new Uint8Array(256), SA);
  row("RS256", "bad: exponent 3 supplied", false, n!, Uint8Array.of(3), msg, sig, SA);
  row("RS256", "bad: exponent 65537 with a leading zero byte is still 65537 (accepted by value)", true, n!, Uint8Array.of(0, 1, 0, 1), msg, sig, SA);
}
// RSA signatures built OUTSIDE the authenticator, so the padding can be wrong in chosen ways: raw private-key operation with BigInt on a Web Crypto key.
{
  const kp = await crypto.subtle.generateKey({ name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: Uint8Array.of(1, 0, 1), hash: "SHA-256" }, true, ["sign", "verify"]);
  const jwk = await crypto.subtle.exportKey("jwk", kp.privateKey);
  const n = fromB64u(jwk.n!);
  const e = fromB64u(jwk.e!);
  const nBig = bigOf(n);
  const dBig = bigOf(fromB64u(jwk.d!));
  const modexp = (b: bigint, x: bigint, m: bigint) => {
    let r = 1n;
    b %= m;
    while (x > 0n) {
      if (x & 1n) r = (r * b) % m;
      x >>= 1n;
      b = (b * b) % m;
    }
    return r;
  };
  const msg = crypto.getRandomValues(new Uint8Array(69));
  const h = await sha256(msg);
  const prefix = fromHex("3031300d060960864801650304020105000420");
  const rawSign = (em: Uint8Array) => bytesOf(modexp(bigOf(em), dBig, nBig), 256);
  const k = 256;
  const emGood = concat(Uint8Array.of(0, 1), new Uint8Array(k - 3 - prefix.length - 32).fill(0xff), Uint8Array.of(0), prefix, h);
  row("RS256", "valid: hand-built EMSA-PKCS1-v1_5 signed with a raw private-key operation (checks the fixture path)", true, n, e, msg, rawSign(emGood), "bigint-raw-rsa");
  // Bleichenbacher-shaped: a SHORT padding string and four garbage bytes after the hash, so a parser that stops at the DigestInfo accepts it
  const emTrailing = concat(Uint8Array.of(0, 1), new Uint8Array(k - 3 - prefix.length - 32 - 4).fill(0xff), Uint8Array.of(0), prefix, h, Uint8Array.of(0xde, 0xad, 0xbe, 0xef));
  row("RS256", "bad: padding string shortened and 4 garbage bytes after the hash (lenient-parser forgery shape)", false, n, e, msg, rawSign(emTrailing), "bigint-raw-rsa");
  // a zero byte inside the 0xff padding string
  const emHole = Uint8Array.from(emGood);
  emHole[20] = 0x00;
  row("RS256", "bad: a 0x00 byte inside the 0xff padding string", false, n, e, msg, rawSign(emHole), "bigint-raw-rsa");
  // block type 0x02 instead of 0x01
  const emType = Uint8Array.from(emGood);
  emType[1] = 0x02;
  row("RS256", "bad: block type 0x02", false, n, e, msg, rawSign(emType), "bigint-raw-rsa");
  // a properly padded signature over a SHA-384 DigestInfo (RSASSA-PKCS1-v1_5/SHA-384 straight from Web Crypto): valid RSA, wrong hash for RS256
  const sig384 = new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5", await crypto.subtle.importKey("jwk", { ...jwk, alg: undefined }, { name: "RSASSA-PKCS1-v1_5", hash: "SHA-384" }, false, ["sign"]), msg as Uint8Array<ArrayBuffer>));
  row("RS256", "bad: a valid PKCS#1 v1.5 signature but over a SHA-384 DigestInfo", false, n, e, msg, sig384, "webcrypto");
}
// a 4096-bit key: not what authenticators emit, but the cost ceiling the 'RSA, 2048 bits or more' rule allows
{
  const kp = await crypto.subtle.generateKey({ name: "RSASSA-PKCS1-v1_5", modulusLength: 4096, publicExponent: Uint8Array.of(1, 0, 1), hash: "SHA-256" }, true, ["sign", "verify"]);
  const jwk = await crypto.subtle.exportKey("jwk", kp.publicKey);
  const msg = crypto.getRandomValues(new Uint8Array(69));
  const sig = new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5", kp.privateKey, msg as Uint8Array<ArrayBuffer>));
  row("RS256", "valid (4096-bit; the upper bound the verifier accepts)", true, fromB64u(jwk.n!), fromB64u(jwk.e!), msg, sig, "webcrypto");
}
console.log("COMMIT;");
