-- 05_own_row_matrix.sql
-- build plan §4.7.7 (docs/golf-trails/02-build-plan.md:1315-1330):
-- "Player A | reads B's plays through any view | 0 rows" (line 1330), applied
-- exhaustively across every player-facing api.my_* view (§4.7 item 3, line 1246:
-- "Every player-facing view filters user_id = auth.uid() in its own WHERE") and
-- every non-owner actor: another player, staff, manager, operator, admin, anon.
-- Generated by hand from tools/db/test.sh's fixture set in supabase/tests/helpers.sql
-- (each view has exactly one row seeded, owned by player A, EXCEPT my_entitlement
-- and my_offer_code, which the B3 gate-round-2 fixtures widened to 2 each — an
-- activated/redeemable row plus a redeemed one, and a plain/redeemed one, so
-- private.delete_my_data has both states to exercise).
--
-- api.my_profile is special-cased: every actor has (or may have) their OWN
-- profile row (player B does, per the fixtures), so "sees 0 rows" is the wrong
-- assertion there. The real isolation property under test for my_profile is
-- "never returns player A's row", which is what is asserted instead.

BEGIN;
SELECT plan(98);

-- api.my_profile
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile), 1, 'owner (player A) sees exactly 1 row(s) via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile WHERE user_id = '00000000-0000-0000-0000-00000000000a'), 0, 'player_b never sees player A''s row via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile WHERE user_id = '00000000-0000-0000-0000-00000000000a'), 0, 'staff_x never sees player A''s row via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile WHERE user_id = '00000000-0000-0000-0000-00000000000a'), 0, 'manager_x never sees player A''s row via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile WHERE user_id = '00000000-0000-0000-0000-00000000000a'), 0, 'operator_t never sees player A''s row via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_profile WHERE user_id = '00000000-0000-0000-0000-00000000000a'), 0, 'admin never sees player A''s row via api.my_profile');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_profile', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_profile');
SELECT tests.clear_actor();

-- api.my_device
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 1, 'owner (player A) sees exactly 1 row(s) via api.my_device');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 0, 'player_b sees 0 rows via api.my_device (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 0, 'staff_x sees 0 rows via api.my_device (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 0, 'manager_x sees 0 rows via api.my_device (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 0, 'operator_t sees 0 rows via api.my_device (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_device), 0, 'admin sees 0 rows via api.my_device (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_device', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_device');
SELECT tests.clear_actor();

-- api.my_push_token
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 1, 'owner (player A) sees exactly 1 row(s) via api.my_push_token');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 0, 'player_b sees 0 rows via api.my_push_token (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 0, 'staff_x sees 0 rows via api.my_push_token (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 0, 'manager_x sees 0 rows via api.my_push_token (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 0, 'operator_t sees 0 rows via api.my_push_token (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_push_token), 0, 'admin sees 0 rows via api.my_push_token (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_push_token', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_push_token');
SELECT tests.clear_actor();

-- api.my_evidence
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 1, 'owner (player A) sees exactly 1 row(s) via api.my_evidence');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 0, 'player_b sees 0 rows via api.my_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 0, 'staff_x sees 0 rows via api.my_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 0, 'manager_x sees 0 rows via api.my_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 0, 'operator_t sees 0 rows via api.my_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_evidence), 0, 'admin sees 0 rows via api.my_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_evidence', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_evidence');
SELECT tests.clear_actor();

-- api.my_purchase_evidence
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 1, 'owner (player A) sees exactly 1 row(s) via api.my_purchase_evidence');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 0, 'player_b sees 0 rows via api.my_purchase_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 0, 'staff_x sees 0 rows via api.my_purchase_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 0, 'manager_x sees 0 rows via api.my_purchase_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 0, 'operator_t sees 0 rows via api.my_purchase_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_purchase_evidence), 0, 'admin sees 0 rows via api.my_purchase_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_purchase_evidence', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_purchase_evidence');
SELECT tests.clear_actor();

-- api.my_play
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 1, 'owner (player A) sees exactly 1 row(s) via api.my_play');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 0, 'player_b sees 0 rows via api.my_play (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 0, 'staff_x sees 0 rows via api.my_play (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 0, 'manager_x sees 0 rows via api.my_play (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 0, 'operator_t sees 0 rows via api.my_play (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play), 0, 'admin sees 0 rows via api.my_play (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_play', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_play');
SELECT tests.clear_actor();

-- api.my_play_evidence
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 1, 'owner (player A) sees exactly 1 row(s) via api.my_play_evidence');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 0, 'player_b sees 0 rows via api.my_play_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 0, 'staff_x sees 0 rows via api.my_play_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 0, 'manager_x sees 0 rows via api.my_play_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 0, 'operator_t sees 0 rows via api.my_play_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_play_evidence), 0, 'admin sees 0 rows via api.my_play_evidence (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_play_evidence', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_play_evidence');
SELECT tests.clear_actor();

-- api.my_achievement
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 1, 'owner (player A) sees exactly 1 row(s) via api.my_achievement');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 0, 'player_b sees 0 rows via api.my_achievement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 0, 'staff_x sees 0 rows via api.my_achievement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 0, 'manager_x sees 0 rows via api.my_achievement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 0, 'operator_t sees 0 rows via api.my_achievement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_achievement), 0, 'admin sees 0 rows via api.my_achievement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_achievement', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_achievement');
SELECT tests.clear_actor();

-- api.my_marker_credit
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 1, 'owner (player A) sees exactly 1 row(s) via api.my_marker_credit');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 0, 'player_b sees 0 rows via api.my_marker_credit (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 0, 'staff_x sees 0 rows via api.my_marker_credit (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 0, 'manager_x sees 0 rows via api.my_marker_credit (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 0, 'operator_t sees 0 rows via api.my_marker_credit (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_marker_credit), 0, 'admin sees 0 rows via api.my_marker_credit (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_marker_credit', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_marker_credit');
SELECT tests.clear_actor();

-- api.my_entitlement
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 2, 'owner (player A) sees exactly 2 row(s) via api.my_entitlement');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 0, 'player_b sees 0 rows via api.my_entitlement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 0, 'staff_x sees 0 rows via api.my_entitlement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 0, 'manager_x sees 0 rows via api.my_entitlement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 0, 'operator_t sees 0 rows via api.my_entitlement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_entitlement), 0, 'admin sees 0 rows via api.my_entitlement (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_entitlement', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_entitlement');
SELECT tests.clear_actor();

-- api.my_offer_code
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 2, 'owner (player A) sees exactly 2 row(s) via api.my_offer_code');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 0, 'player_b sees 0 rows via api.my_offer_code (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 0, 'staff_x sees 0 rows via api.my_offer_code (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 0, 'manager_x sees 0 rows via api.my_offer_code (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 0, 'operator_t sees 0 rows via api.my_offer_code (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_offer_code), 0, 'admin sees 0 rows via api.my_offer_code (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_offer_code', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_offer_code');
SELECT tests.clear_actor();

-- api.my_booking
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 1, 'owner (player A) sees exactly 1 row(s) via api.my_booking');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 0, 'player_b sees 0 rows via api.my_booking (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 0, 'staff_x sees 0 rows via api.my_booking (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 0, 'manager_x sees 0 rows via api.my_booking (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 0, 'operator_t sees 0 rows via api.my_booking (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_booking), 0, 'admin sees 0 rows via api.my_booking (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_booking', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_booking');
SELECT tests.clear_actor();

-- api.my_connector_account
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 1, 'owner (player A) sees exactly 1 row(s) via api.my_connector_account');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 0, 'player_b sees 0 rows via api.my_connector_account (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 0, 'staff_x sees 0 rows via api.my_connector_account (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 0, 'manager_x sees 0 rows via api.my_connector_account (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 0, 'operator_t sees 0 rows via api.my_connector_account (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_connector_account), 0, 'admin sees 0 rows via api.my_connector_account (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_connector_account', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_connector_account');
SELECT tests.clear_actor();

-- api.my_attestation
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000a'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 1, 'owner (player A) sees exactly 1 row(s) via api.my_attestation');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-00000000000b'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 0, 'player_b sees 0 rows via api.my_attestation (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-1000000000a1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 0, 'staff_x sees 0 rows via api.my_attestation (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-2000000000b1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 0, 'manager_x sees 0 rows via api.my_attestation (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-3000000000c1'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 0, 'operator_t sees 0 rows via api.my_attestation (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('authenticated', tests.claims('00000000-0000-0000-0000-4000000000d0'::uuid));
SELECT is((SELECT count(*)::int FROM api.my_attestation), 0, 'admin sees 0 rows via api.my_attestation (not their own)');
SELECT tests.clear_actor();
SELECT tests.authenticate_as('anon', '{}'::jsonb);
SELECT throws_ok('SELECT count(*) FROM api.my_attestation', '42501', NULL, 'anon is denied (no SELECT grant) on api.my_attestation');
SELECT tests.clear_actor();

SELECT * FROM finish();
ROLLBACK;
