/// <reference types="expo/types" />

// NOTE: This file is generated by Expo's template and should not be edited.
// It brings in `process.env.EXPO_PUBLIC_*`, `require`, and the other Metro
// globals for the APP program (tsconfig.json), which deliberately excludes
// @types/node.
