// @ts-check
/**
 * The Content Security Policy of `apps/partners` and the `_headers` file that carries it (docs/security/partner-auth-design.md 4.6).
 *
 * Emitted TWICE from one function: as the `Content-Security-Policy` response header (`dist/_headers`, the way apps/site does it) and as a
 * `<meta http-equiv>` in `index.html`, so a static host that ignores `_headers` still serves the page under the policy. `frame-ancestors` is
 * ignored in a meta element (and logs a console error), so the meta form leaves it out; the header form has it.
 *
 *   default-src 'none'            nothing is allowed unless a directive below names it
 *   script-src 'self'             our own bundle only: no inline script, no eval, no third-party origin
 *   style-src 'self'              an external stylesheet only: no `<style>`, no `style=""` attribute
 *   img-src 'self'                the favicon (no `data:`: nothing in the page needs it)
 *   connect-src <API origin>      the partners API and nothing else (not even 'self': the page fetches nothing from its own origin).
 *                                 It never names the PostgREST host: this page does not talk to the data API (design 4.6)
 *   manifest-src 'self'           the web app manifest
 *   worker-src 'none'             S7a ships no service worker (README: why)
 *   object-src 'none', base-uri 'none', form-action 'none', frame-ancestors 'none'
 *   require-trusted-types-for 'script' + trusted-types 'none'
 *                                 every DOM string sink (innerHTML, script.src, eval, ...) must receive a TrustedType, and no policy may be created,
 *                                 so none can: the code uses `textContent` only. Chromium enforces this today; Safari's support is [unverified]
 *                                 and an unsupporting browser simply ignores both directives.
 *
 * Departures from the design's section 4.6 list, all STRICTER: `connect-src` drops 'self'; `img-src` drops `data:`; `worker-src` is 'none', not 'self'.
 */

/**
 * @param {string} apiOrigin the exact origin the page may connect to
 * @param {{ meta?: boolean }} [opts]
 */
export function buildCsp(apiOrigin, opts = {}) {
  const directives = [
    `default-src 'none'`,
    `script-src 'self'`,
    `style-src 'self'`,
    `img-src 'self'`,
    `connect-src ${apiOrigin}`,
    `manifest-src 'self'`,
    `worker-src 'none'`,
    `object-src 'none'`,
    `base-uri 'none'`,
    `form-action 'none'`,
    ...(opts.meta ? [] : [`frame-ancestors 'none'`]),
    `require-trusted-types-for 'script'`,
    `trusted-types 'none'`,
  ];
  return directives.join("; ");
}

/**
 * The generated `_headers` file (Cloudflare Pages syntax, as apps/site). One `/*` block carries the security headers; the hashed assets add a long cache
 * lifetime in their own block (no header name is repeated across blocks: Pages joins repeated names with a comma instead of replacing them).
 *
 * @param {string} apiOrigin
 */
export function buildHeadersFile(apiOrigin) {
  return (
    `# GENERATED by scripts/build.mjs - do not hand-edit.\n` +
    `/*\n` +
    `  Content-Security-Policy: ${buildCsp(apiOrigin)}\n` +
    `  X-Content-Type-Options: nosniff\n` +
    `  Referrer-Policy: no-referrer\n` +
    `  Permissions-Policy: publickey-credentials-get=(self), publickey-credentials-create=(self), camera=(), microphone=(), geolocation=(), payment=(), usb=()\n` +
    `  Cross-Origin-Opener-Policy: same-origin\n` +
    `  Cross-Origin-Resource-Policy: same-origin\n` +
    `  X-Robots-Tag: noindex, nofollow\n` +
    `\n` +
    `/assets/*\n` +
    `  Cache-Control: public, max-age=31536000, immutable\n`
  );
}
